server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenaichenet/springcloud-config.git #不使用ssh
          #uri: git@github.com:chenaichenet/springcloud-config.git #填写你自己的github路径
          search-paths:   #搜索目录（仓库）
            - springcloud-config
      label: master   #读取分支

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

#rabbitMQ相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'