server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-08-16T08:41:27.049083200+08:00[Asia/Shanghai]  #表示在这个时间以后，请求访问才有效果
#            - Before=2020-08-17T08:41:27.049083200+08:00[Asia/Shanghai] #表示在这个时间之前，请求访问才有效果
#            - Between=2020-08-16T08:41:27.049083200+08:00[Asia/Shanghai],2020-08-17T08:41:27.049083200+08:00[Asia/Shanghai] #在特定时间内
#            - Cookie=username,test #cookie名为username，值为test（可以设置正则表达式）
#            - Hander=X-Request-Id, \d+  #请求头要有 X-Request-Id 属性并且值为整数的正则表达式
#            - Host=**.springcloud.com   #主机地址
#            - Method=GET  #请求类型
#            - Query=username, \d+   #要有参数名称并且是正整数才能路由
#      default-filters:
#        - AddRequestParamter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-Id,值为1024


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka